In [1]:
from pandas import Series, DataFrame
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df1 = pd.read_csv("brasil-real-estate-1.csv")
df2 = pd.read_csv("brasil-real-estate-2.csv")

In [3]:
df1.dropna(inplace =True)
df1.head()

,property_type,place_with_parent_names,region,lat-lon,area_m2,price_usd
0,apartment,|Brasil|Alagoas|Maceió|,Northeast,"-9.6443051,-35.7088142",110.0,"$187,230.85"
1,apartment,|Brasil|Alagoas|Maceió|,Northeast,"-9.6430934,-35.70484",65.0,"$81,133.37"
2,house,|Brasil|Alagoas|Maceió|,Northeast,"-9.6227033,-35.7297953",211.0,"$154,465.45"
3,apartment,|Brasil|Alagoas|Maceió|,Northeast,"-9.622837,-35.719556",99.0,"$146,013.20"
4,apartment,|Brasil|Alagoas|Maceió|,Northeast,"-9.654955,-35.700227",55.0,"$101,416.71"

In [4]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11551 entries, 0 to 12833
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   property_type            11551 non-null  object
 1   place_with_parent_names  11551 non-null  object
 2   region                   11551 non-null  object
 3   lat-lon                  11551 non-null  object
 4   area_m2                  11551 non-null  float64
 5   price_usd                11551 non-null  object
dtypes: float64(1), object(5)
memory usage: 406.1+ KB

In [5]:
df1["lat-lon"].head()

0    -9.6443051,-35.7088142
1      -9.6430934,-35.70484
2    -9.6227033,-35.7297953
3      -9.622837,-35.719556
4      -9.654955,-35.700227
Name: lat-lon, dtype: object

In [6]:
df1["lat-lon"].str.split(",", expand =True).head()

            0            1
0  -9.6443051  -35.7088142
1  -9.6430934    -35.70484
2  -9.6227033  -35.7297953
3   -9.622837   -35.719556
4   -9.654955   -35.700227

In [7]:
df1[["lat", "lon"]] = df1["lat-lon"].str.split(",", expand =True).astype(float)
df1.head()

,property_type,place_with_parent_names,region,lat-lon,area_m2,price_usd,lat,lon
0,apartment,|Brasil|Alagoas|Maceió|,Northeast,"-9.6443051,-35.7088142",110.0,"$187,230.85",-9.644305,-35.708814
1,apartment,|Brasil|Alagoas|Maceió|,Northeast,"-9.6430934,-35.70484",65.0,"$81,133.37",-9.643093,-35.704840
2,house,|Brasil|Alagoas|Maceió|,Northeast,"-9.6227033,-35.7297953",211.0,"$154,465.45",-9.622703,-35.729795
3,apartment,|Brasil|Alagoas|Maceió|,Northeast,"-9.622837,-35.719556",99.0,"$146,013.20",-9.622837,-35.719556
4,apartment,|Brasil|Alagoas|Maceió|,Northeast,"-9.654955,-35.700227",55.0,"$101,416.71",-9.654955,-35.700227

In [8]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11551 entries, 0 to 12833
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   property_type            11551 non-null  object
 1   place_with_parent_names  11551 non-null  object
 2   region                   11551 non-null  object
 3   lat-lon                  11551 non-null  object
 4   area_m2                  11551 non-null  float64
 5   price_usd                11551 non-null  object
 6   lat                      11551 non-null  float64
 7   lon                      11551 non-null  float64
dtypes: float64(3), object(5)
memory usage: 586.6+ KB

In [9]:
df1["States"]  = df1["place_with_parent_names"].str.split("|", expand = True).drop(columns=[0,1,3,4,5])
df1.tail()

,property_type,place_with_parent_names,region,lat-lon,area_m2,price_usd,lat,lon,States
12828,apartment,|Brasil|Pernambuco|Recife|,Northeast,"-8.044497,-34.909519",74.0,"$134,182.11",-8.044497,-34.909519,Pernambuco
12829,apartment,|Brasil|Pernambuco|Recife|,Northeast,"-8.056418,-34.909309",91.0,"$174,748.79",-8.056418,-34.909309,Pernambuco
12830,apartment,|Brasil|Pernambuco|Recife|,Northeast,"-8.1373477,-34.909181",115.0,"$115,459.02",-8.137348,-34.909181,Pernambuco
12831,apartment,|Brasil|Pernambuco|Recife|Boa Viagem|,Northeast,"-8.1136717,-34.896252",76.0,"$137,302.62",-8.113672,-34.896252,Pernambuco
12833,apartment,|Brasil|Pernambuco|Recife|Boa Viagem|,Northeast,"-8.0578381,-34.882897",99.0,"$168,507.77",-8.057838,-34.882897,Pernambuco

##Use the "place_with_parent_names" column to create a "state"## 
##column for df1. (Note that the state name always appears after "|Brasil|" in each string.)##

In [10]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11551 entries, 0 to 12833
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   property_type            11551 non-null  object
 1   place_with_parent_names  11551 non-null  object
 2   region                   11551 non-null  object
 3   lat-lon                  11551 non-null  object
 4   area_m2                  11551 non-null  float64
 5   price_usd                11551 non-null  object
 6   lat                      11551 non-null  float64
 7   lon                      11551 non-null  float64
 8   States                   11551 non-null  object
dtypes: float64(3), object(6)
memory usage: 631.7+ KB

##3. Transform the "price_usd" column of df1 so that all values are floating-point numbers instead of strings.

In [11]:
df1["price_usd"] = df1["price_usd"].str.replace("$", "").str.replace(",", "").astype(float)
df1.head()

,property_type,place_with_parent_names,region,lat-lon,area_m2,price_usd,lat,lon,States
0,apartment,|Brasil|Alagoas|Maceió|,Northeast,"-9.6443051,-35.7088142",110.0,187230.85,-9.644305,-35.708814,Alagoas
1,apartment,|Brasil|Alagoas|Maceió|,Northeast,"-9.6430934,-35.70484",65.0,81133.37,-9.643093,-35.704840,Alagoas
2,house,|Brasil|Alagoas|Maceió|,Northeast,"-9.6227033,-35.7297953",211.0,154465.45,-9.622703,-35.729795,Alagoas
3,apartment,|Brasil|Alagoas|Maceió|,Northeast,"-9.622837,-35.719556",99.0,146013.20,-9.622837,-35.719556,Alagoas
4,apartment,|Brasil|Alagoas|Maceió|,Northeast,"-9.654955,-35.700227",55.0,101416.71,-9.654955,-35.700227,Alagoas